logging.charset.console=UTF-8
logging.charset.file=UTF-8

spring.application.name=finance-tracker
server.port=9001

#Swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
spring.web.resources.add-mappings=true
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true

#PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5433/financedb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=none
#spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Liquibase
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

spring.liquibase.enabled=true
logging.level.liquibase=DEBUG
#logging.level.org.springframework.boot.autoconfigure=DEBUG

#Aspect
logging.level.kmull.finance_tracker.aspect=DEBUG
transaction.max-amount=50000

#Logowanie
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG

#Scheduler
scheduler.transaction-stats.cron=0 * * * * *

#Redis
spring.cache.type=redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.cache.redis.time-to-live=60000
logging.level.org.springframework.data.redis=DEBUG
spring.data.redis.repositories.enabled=false