spring.application.name=finance-tracker
server.port=9001

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5433/financedb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Liquibase
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

spring.liquibase.enabled=true
logging.level.liquibase=DEBUG
#logging.level.org.springframework.boot.autoconfigure=DEBUG

